export const dataDB = [
    {
        id: 1,
        name: "Alitas fritas",
        urlImages: "./images/alitasfritas.jpg",
        stock: 5,
        price: 1000,
    },
    {
        id: 2,
        name: "Bastoncitos",
        urlImages: "./images/bastones.jpeg",
        stock: 6,
        price: 2000,
    },
    {
        id: 3,
        name: "Big burguer",
        urlImages: "./images/bigburger.jpg",
        stock: 7,
        price: 3000,
    },
    {
        id: 4,
        name: "Classic",
        urlImages: "./images/classic.jpg",
        stock: 8,
        price: 4000,
    },
    {
        id: 5,
        name: "Empanadas",
        urlImages: "./images/empanadas.jpeg",
        stock: 9,
        price: 5000,
    },
    {
        id: 6,
        name: "Fritas",
        urlImages: "./images/fritas.jpeg",
        stock: 10,
        price: 6000,
    },
    {
        id: 7,
        name: "Honet mustad",
        urlImages: "./images/honetMustad.jpg",
        stock: 11,
        price: 7000,
    },
    {
        id: 8,
        name: "Pizza Napo",
        urlImages: "./images/pizzaNapo.jpg",
        stock: 13,
        price: 9000,
    },
    {
        id: 9,
        name: "Provoleta",
        urlImages: "./images/provoleta.jpg",
        stock: 13,
        price: 9000,
    },
    {
        id: 10,
        name: "Sandwich",
        urlImages: "./images/sandwich.jpeg",
        stock: 13,
        price: 9000,
    },
    {
        id: 11,
        name: "Tabla de fritos",
        urlImages: "./images/tablaDeFritos.jpg",
        stock: 13,
        price: 9000,
    },
    {
        id: 12,
        name: "Veggie",
        urlImages: "./images/veggie.jpg",
        stock: 13,
        price: 9000,
    },
];
